name: gitee-page-reload
on: page_build
jobs:
  reload-pages:
    runs-on: ubuntu-latest
    steps:
      - name: reload
        uses: mizuka-wu/gitee-pages-action@v1.0.0
        with:
          repository: Floating-Ocean/blog
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: main
          https: true
