name: gitee-page-reload
on: page_build
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Floating-Ocean/blog.git"
          destination-repo: "git@gitee.com:Floating-Ocean/blog.git"
  reload-pages:
    runs-on: ubuntu-latest
    steps:
      - name: reload
        uses: mizuka-wu/gitee-pages-action@v1.0.0
        with:
          repository: Floating-Ocean/blog
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: main
          https: true
