name: push-to-merge-collection
on: page_build

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      
    steps:
      - name: Self Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Remote Checkout
        uses: actions/checkout@v3
        with:
          repository: Floating-Ocean/Merged-Website
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Commit to Merge Collection
        run: |
          git config --global user.email "sea113290980@qq.com"
          git config --global user.name "Floating-Ocean"
          git clone https://github.com/Floating-Ocean/Merged-Website.git merged-repo
          cd merged-repo
          rm -rf blog
          git clone https://github.com/Floating-Ocean/blog.git -b gh-pages blog
          cd blog
          rm -rf .git
          cd ..
          git add .
          git commit -a -m "First update blog"
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          repository: Floating-Ocean/Merged-Website
          branch: main
          force: true
          github_token: ${{ secrets.CLONE_TOKEN }}
