name: push-to-merge-collection
on: page_build

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      
    steps:
      - name: Self Checkout
        uses: actions/checkout@master
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Remote Checkout
        uses: actions/checkout@master
        with:
          repository: Floating-Ocean/Merged-Website
          ref: main
          fetch-depth: 0
          persist-credentials: false
          
      - name: Commit to Merge Collection
        run: |
          git config --global user.email "sea113290980@qq.com"
          git config --global user.name "Floating-Ocean"
          git clone https://github.com/Floating-Ocean/Merged-Website.git merged-repo
          cd merged-repo
          rm -rf blog/*
          git clone https://github.com/Floating-Ocean/blog.git -b gh-pages blog
          cd blog
          rm -rf .git/*
          rm -rf .git/
          cd ..
          pwd
          git add *
          git commit -m "First update blog"
          
  apply-push: 
    runs-on: ubuntu-latest
    needs: clone-repo
    permissions:
      contents: write
      repository-projects: write
      
    steps:
      - name: Self Checkout
        uses: actions/checkout@master
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Remote Checkout
        uses: actions/checkout@master
        with:
          repository: Floating-Ocean/Merged-Website
          ref: main
          fetch-depth: 0
          persist-credentials: false
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          repository: Floating-Ocean/Merged-Website
          branch: main
          force: true
          github_token: ${{ secrets.CLONE_TOKEN }}
          directory: /home/runner/work/blog/blog/merged-repo/
