name: push-to-merge-collection
on: page_build

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Self Checkout
        uses: actions/checkout@v2

      - name: Remote Checkout
        uses: actions/checkout@v2
        with:
          repository: Floating-Ocean/Merged-Website

      - name: Push to Merge Collection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git config --global user.name 'Floating-Ocean'
          git config --global user.email 'sea113290980@qq.com'
          git clone https://github.com/Floating-Ocean/Merged-Website.git merged-repo
          cd merged-repo
          rm -rf blog
          git clone https://github.com/Floating-Ocean/blog.git -b gh-pages blog
          cd blog
          rm -rf .git
          cd ..
          git add .
          git commit -m "First update blog"
          ssh -T git@github.com
          git remote add merge git@github.com:Floating-Ocean/Merged-Website.git
          git push -u merge main
