name: push-to-merge-collection
on: page_build

permissions:
  contents: write
  repository-projects: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Self Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Remote Checkout
        uses: actions/checkout@v3
        with:
          repository: Floating-Ocean/Merged-Website

      - name: Commit to Merge Collection
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://github.com/Floating-Ocean/Merged-Website.git merged-repo
          cd merged-repo
          rm -rf blog
          git clone https://github.com/Floating-Ocean/blog.git -b gh-pages blog
          cd blog
          rm -rf .git
          cd ..
          git add .
          git commit -m "First update blog"
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          repository: Floating-Ocean/Merged-Website
          branch: main
          force: true
